#!/usr/bin/env -S python3 -b -B
# -*- python -*-
import sys, os, re, shutil
import argparse
SRCDIR = os.path.dirname (os.path.dirname (os.path.abspath (__file__)))

def main():
  # parse args
  parser = argparse.ArgumentParser (description = "Generate test case Makefile for Imagewmark.")
  parser.add_argument ("imagedir", help = "Directory containing input images.")
  parser.add_argument ("-c", "--clean", action = "store_true", help = "Clean output directory before generating tests.")
  parser.add_argument ("-O", "--outputdir", help = "Directory to place generated tests. Defaults to CWD.", default = ".")
  args = parser.parse_args()
  output_dir = os.path.abspath (args.outputdir)
  imagedir = os.path.abspath (args.imagedir)
  if not os.path.isdir (imagedir):
    print (f"Error: Directory not found: {imagedir}", file = sys.stderr)
    sys.exit (1)
  # clear and mkdir the output_dir
  if args.clean and os.path.isdir (output_dir):
    shutil.rmtree (output_dir)
  os.makedirs (output_dir, exist_ok = True)
  # generate and configure Makefile
  inmk, outmk = os.path.join (SRCDIR, 'tests', 'Makefile'), os.path.join (output_dir, 'Makefile')
  with open (inmk, 'r+', encoding='utf-8') as src, open (outmk, 'w', encoding='utf-8') as dst:
    content = src.read()
    content = re.sub (r'^SRCDIR\s*\?=.*', f'SRCDIR := {SRCDIR}', content, 0, re.M)
    dst.write (content)
  # Placeholder for test generation logic
  print (f"Generating tests using images from: {imagedir} into {output_dir}")

if __name__ == "__main__":
  main()
