# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

# Linting: xclip -sel c <.github/workflows/ci-builds.yml # https://rhysd.github.io/actionlint/

on:
  push:
    branches: ['trunk', 'wip/**']
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+*' ]
  pull_request:
    branches: ['trunk', 'wip/**']  # Only run PRs targeting these branches

jobs:

  Alpine-CI:
    runs-on: ubuntu-latest
    container: { image: 'ghcr.io/tim-janik/imagewmark-ci:alpine-latest', options: --user runner }
    steps:
    - { uses: actions/checkout@v4.1.1, with: { fetch-depth: 0, submodules: recursive } }
    - run: git fetch -f --tags          # Fix actions/checkout#290
    - run: |
        src/version.sh
        git describe --always --long
    - run: make -j`nproc`
    - run: |
        src/version.sh >&2 | tee Alpine-CI.txt
        make -j`nproc` check >&2 | tee -a Alpine-CI.txt
    - { uses: actions/upload-artifact@v4, with: { name: assets, path: Alpine-CI.txt } }

  Ping-IRC:
    if: always()	# github.event_name != 'pull_request'
    needs: [Alpine-CI]
    runs-on: ubuntu-latest
    steps:
    - { uses: actions/checkout@v4.1.1,  with: { fetch-depth: 0 } }
    - run: git fetch -f --tags          # Fix actions/checkout#290
    - name: Check-Jobs
      run: |
        echo 'Alpine-CI:${{ needs.Alpine-CI.result }}'
        [[ ${{ needs.Alpine-CI.result }}    =~ success|skipped ]]
    - name: Ping-IRC
      if: ${{ always() && !env.ACT }}
      run: |
        .github/workflows/ircbot.py -q -j "#Anklang" -G -S '${{ job.status }}' "$(git log -1 --format=%s)"
